//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeBookFinderService.localhost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IBookFinderService")]
    public interface IBookFinderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookFinderService/GetBookList", ReplyAction="http://tempuri.org/IBookFinderService/GetBookListResponse")]
        ConsumeBookFinderService.localhost.Book[] GetBookList(string sort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookFinderService/GetBookList", ReplyAction="http://tempuri.org/IBookFinderService/GetBookListResponse")]
        System.Threading.Tasks.Task<ConsumeBookFinderService.localhost.Book[]> GetBookListAsync(string sort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookFinderService/FindBook", ReplyAction="http://tempuri.org/IBookFinderService/FindBookResponse")]
        ConsumeBookFinderService.localhost.Book FindBook(string partialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookFinderService/FindBook", ReplyAction="http://tempuri.org/IBookFinderService/FindBookResponse")]
        System.Threading.Tasks.Task<ConsumeBookFinderService.localhost.Book> FindBookAsync(string partialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookFinderService/ToBookString", ReplyAction="http://tempuri.org/IBookFinderService/ToBookStringResponse")]
        string ToBookString(ConsumeBookFinderService.localhost.Book b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookFinderService/ToBookString", ReplyAction="http://tempuri.org/IBookFinderService/ToBookStringResponse")]
        System.Threading.Tasks.Task<string> ToBookStringAsync(ConsumeBookFinderService.localhost.Book b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookFinderServiceChannel : ConsumeBookFinderService.localhost.IBookFinderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookFinderServiceClient : System.ServiceModel.ClientBase<ConsumeBookFinderService.localhost.IBookFinderService>, ConsumeBookFinderService.localhost.IBookFinderService {
        
        public BookFinderServiceClient() {
        }
        
        public BookFinderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookFinderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookFinderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookFinderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsumeBookFinderService.localhost.Book[] GetBookList(string sort) {
            return base.Channel.GetBookList(sort);
        }
        
        public System.Threading.Tasks.Task<ConsumeBookFinderService.localhost.Book[]> GetBookListAsync(string sort) {
            return base.Channel.GetBookListAsync(sort);
        }
        
        public ConsumeBookFinderService.localhost.Book FindBook(string partialName) {
            return base.Channel.FindBook(partialName);
        }
        
        public System.Threading.Tasks.Task<ConsumeBookFinderService.localhost.Book> FindBookAsync(string partialName) {
            return base.Channel.FindBookAsync(partialName);
        }
        
        public string ToBookString(ConsumeBookFinderService.localhost.Book b) {
            return base.Channel.ToBookString(b);
        }
        
        public System.Threading.Tasks.Task<string> ToBookStringAsync(ConsumeBookFinderService.localhost.Book b) {
            return base.Channel.ToBookStringAsync(b);
        }
    }
}
